name: zloz_mnie
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  animations: ^2.0.7
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  intl: ^0.17.0
  lawsuit_repository: 
    path: packages/lawsuit_repository
  money_input_formatter: ^2.0.0
  time: ^2.1.3
  zloz_mnie_api_client:
    path: packages/zloz_mnie_api_client



dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
